
# # Default colors
# [colors.primary]
# background = '#1d2021'
# # background = '#282828'
# # soft contrast background = = '#32302f'
# foreground = '#ebdbb2'

# # Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'

# # Bright colors
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'

[font]
size = 15
builtin_box_drawing = true

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Fantasque Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"


[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[terminal.shell]
program = "fish"

[window]
opacity = 1.0

[general]
# Colors (Gruvbox dark)
import = [
    # "~/.config/alacritty/themes/themes/base16_default_dark.toml"
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[terminal]
