[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock"]
comment-token = "#"
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
# language-server = { command = "jedi-language-server" }
auto-format = true
formatter = { command = "black", args = ["-", "-q", "--line-length", "120"] }
indent = { tab-width = 4, unit = "    " }

[language.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
#[[language]]
#name = "python"
#scope = "source.python"
#injection-regex = "python"
#file-types = ["py"]
#shebangs = ["python"]
#roots = ["pyproject.toml", "setup.py", "Poetry.lock"]
#comment-token = "#"
#indent = { tab-width = 4, unit = "    " }
#language-server = { command = "ruff-lsp" }
#config = { settings = { args = [] } }

[[language]]
name = "json"
file-types = ["json"]
[language.config]
provideFormatter = false
json.validate.enable = true
json.format.enable = false
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }

[[language]]
name = "markdown"
file-types = ["md", "qmd"]
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }


[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"]}
[language.config]
yaml = { keyOrdering = false, printWidth = 120, proseWrap = "Always" }