# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: Recently updated PRs
  filters: archived:false is:open sort:updated-desc
  type: null
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: Recent Issues
  filters: is:open sort:updated-desc
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
  - command: >
      kitten @ launch --type=overlay-main --cwd current --copy-env gh pr checkout {{.PrNumber}} &&
      REV_BASE=master git review
    key: b
    name: vim git review
  - command: >
      kitten @ launch --type=overlay-main --cwd current --copy-env gh pr checkout {{.PrNumber}} &&
      export BASE_REF=$(git merge-base master {{.HeadRefName}}) &&
      export HEAD_REF=$(git rev-parse {{.HeadRefName}}) &&
      vim -c ":Gclog $BASE_REF...$HEAD_REF"
    key: e
    name: vim fugitive view
  - command: >
      kitten @ launch --type=overlay-main --cwd current --copy-env
      nvim -c ":silent Octo pr edit {{.PrNumber}}"
    key: E
    name: nvim octo review
  branches: []
repoPaths:
  vim/vim: ~/tools/vim
  gcanat/video_reader-rs: ~/projects/video_reader-rs
  wezterm/wezterm: ~/tools/wezterm
  alacritty/alacritty: ~/tools/alacritty
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: delta
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
